ImplexWebApp/Implex/Controllers/MethodsController.cs
using Implex.Models;
using Microsoft.AspNetCore.Mvc;
using LinearAlgebraNumMethods;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;

namespace Implex.Controllers
{
    public class MethodsController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly Options _options;
        private JacobiMethod _jacobiMethodCPP;
        private Models.MatrixMultiplication _multiplicationCPP;

        public MethodsController(IHostingEnvironment environment, Options options)
        {
            _hostingEnvironment = environment;
            _options = options;

            _jacobiMethodCPP = new JacobiMethod();
            _jacobiMethodCPP.Implementation = "C++ is a high-level, general-purpose programming language created by Bjarne Stroustrup as an extension of the C programming language.";

            _multiplicationCPP = new Models.MatrixMultiplication();
            _multiplicationCPP.Implementation = "This method was written on C++ which is a high - level, general - purpose programming language. The first optimization is to re-order the loops to enforce local access in all of the matrices. The standard mapping was then used from a two-dimensional array onto a one-dimensional space. This makes explicit the fact that subscripting in a two-dimensional array requires integer multiplication as well as addition. Replacing subscripting with explicit pointer access allows the elimination of these multiplications.";
        }

        [HttpGet]
        public IActionResult FormJacobiMethod()
        {
            return View(_jacobiMethodCPP);
        }

        [HttpGet]
        public IActionResult FileJacobiMethod()
        {
            return View(_jacobiMethodCPP);
        }

        [HttpPost]
        public IActionResult FormJacobiMethod(JacobiMethod jacobiMethod)
        {
            if (jacobiMethod.VectorB != null && jacobiMethod.MatrixA != null && jacobiMethod.VectorX != null)
            {
                try
                {
                    JacobiMethodCPlusPlus jacobiMethodCPP = new JacobiMethodCPlusPlus();

                    if (jacobiMethodCPP.method(jacobiMethod.MatrixA, jacobiMethod.VectorB, jacobiMethod.VectorX, jacobiMethod.Eps))
                        _jacobiMethodCPP.Result = jacobiMethodCPP.getVectorX();
                    else _jacobiMethodCPP.Result = "It is not strictly diagonally dominant system of linear equations.";
                }
                catch (Exception) { }
            }
            return View(_jacobiMethodCPP);
        }

        [HttpPost]
        public async Task<IActionResult> FileJacobiDownload(JacobiMethod jacobiMethod, IFormFileCollection inputFiles)
        {
            uint id = _options.FileId;
            lock (_options) _options.FileId++;

            List<string> markers = new List<string> { "A", "b", "x"};
            int i = 0;

            string fileResult = _hostingEnvironment.WebRootPath + "\\output_files\\";
            string files = Path.Combine(_hostingEnvironment.WebRootPath, "input_files");

            foreach (var file in inputFiles)
            {
                if (file != null)
                {
                    string filePath = Path.Combine(files, id.ToString() + markers[i] + ".txt");

                    await using FileStream stream = System.IO.File.Create(filePath);
                    await file.CopyToAsync(stream);
                    stream.Close();
                }

                i++;
            }

            try
            {
                JacobiMethodCPlusPlus jacobiMethodCPlusPlus = new JacobiMethodCPlusPlus();
                if (jacobiMethodCPlusPlus.method(id, jacobiMethod.Eps))
                {
                    fileResult += id.ToString() + ".txt";
                }
                else fileResult += "empty.txt";
            }
            catch (Exception) { }

            Stream newStream = new FileStream(fileResult, FileMode.Open);

            return File(newStream, "text/plain");
        }

        [HttpGet]
        public IActionResult FormMatrixMultiplication()
        {
            return View(_multiplicationCPP);
        }

        [HttpPost]
        public IActionResult FormMatrixMultiplication(Models.MatrixMultiplication matrixMultiplication)
        {
            if (matrixMultiplication.MatrixA != null && matrixMultiplication.MatrixB != null)
            {
                try
                {
                    LinearAlgebraNumMethods.MatrixMultiplication multiplication = new LinearAlgebraNumMethods.MatrixMultiplication();
                    _multiplicationCPP.Result = multiplication.multiply(matrixMultiplication.MatrixA, matrixMultiplication.MatrixB);
                }
                catch (Exception) { }
            }
            return View(_multiplicationCPP);
        }

        [HttpGet]
        public IActionResult FileMatrixMultiplication()
        {
            return View(_multiplicationCPP);
        }

        [HttpPost]
        public async Task<IActionResult> FileMatrixMultiplicationDownload(Models.MatrixMultiplication matrixMultiplication, IFormFileCollection inputFiles)
        {
            uint id = _options.FileId;
            lock (_options) _options.FileId++;

            List<string> markers = new List<string> { "A", "B"};
            int i = 0;

            string fileResult = _hostingEnvironment.WebRootPath + "\\output_files\\";
            string files = Path.Combine(_hostingEnvironment.WebRootPath, "input_files");

            foreach (var file in inputFiles)
            {
                if (file != null)
                {
                    string filePath = Path.Combine(files, id.ToString() + markers[i] + ".txt");

                    await using FileStream stream = System.IO.File.Create(filePath);
                    await file.CopyToAsync(stream);
                    stream.Close();
                }

                i++;
            }

            try
            {
                LinearAlgebraNumMethods.MatrixMultiplication multiplication = new LinearAlgebraNumMethods.MatrixMultiplication();
                if (multiplication.multiply(id))
                {
                    fileResult += id.ToString() + ".txt";
                }
                else fileResult += "empty.txt";
            }
            catch(Exception) { }

            Stream newStream = new FileStream(fileResult, FileMode.Open);

            return File(newStream, "text/plain");
        }
    }
}

ImplexWebApp/Implex/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Implex</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container-fluid logo">
        <h3 class="display-3 py-sm-5 mb-0">Numerical Methods Implementations</h3>
    </div>
    <header class="sticky-top">
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm border-bottom box-shadow mb-4">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Implex</a>
            <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="linear-systems" data-toggle="dropdown">Linear Systems</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="Methods" asp-action="FormJacobiMethod">Jacobi C++</a>
                            <a class="dropdown-item" href="#">Gauss C++ (Soon)</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="matrix-operations" data-toggle="dropdown">Matrix Operations</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="Methods" asp-action="FormMatrixMultiplication">Multiplication C++</a>
                            <a class="dropdown-item" href="#">Multiplication C#</a>
                            <a class="dropdown-item" href="#">Addition C++ (Soon)</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="another-methods" data-toggle="dropdown">Another Methods</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Link 1</a>
                            <a class="dropdown-item" href="#">Link 2</a>
                            <a class="dropdown-item" href="#">Link 3</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Implex - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>